const fold = (value) => String(value || "").toLocaleLowerCase("nl").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, " ").trim();
const tokens = (value) => fold(value).split(/\s+/).filter(Boolean);
function distance(a, b) { const row = Array.from({ length: b.length + 1 }, (_, i) => i); for (let i = 1; i <= a.length; i++) { let previous = row[0]; row[0] = i; for (let j = 1; j <= b.length; j++) { const old = row[j]; row[j] = Math.min(row[j] + 1, row[j - 1] + 1, previous + (a[i - 1] === b[j - 1] ? 0 : 1)); previous = old; } } return row[b.length]; }
const routeCanonical = (routes, type, id) => [...routes.entries()].find(([, route]) => route.kind === "entity" && route.entityType === type && route.sourceId === id)?.[0] || null;
export function buildSearchIndex({ generationId, products, growers, routes }) {
    const started = performance.now(); const documents = [];
    for (const entity of [...growers, ...products]) { if (entity.publicationStatus !== "published") continue; const type = entity.entityType; const canonical = routeCanonical(routes, type, entity.sourceId); if (!canonical) continue; const fields = type === "product" ? { name: entity.effective.title, grower: entity.effective.growerName, form: entity.effective.productForm || entity.effective.categoryName || entity.effective.type, subcategory: entity.effective.subCategoryName, variants: entity.effective.variants || [], aliases: entity.editorial?.aliases || entity.source?.aliases || [] } : { name: entity.effective.title, grower: entity.effective.title, aliases: entity.editorial?.aliases || entity.source?.aliases || [] }; const values = [fields.name, fields.grower, fields.form, fields.subcategory, ...(fields.variants || []).map((v) => typeof v === "string" ? v : v.name), ...(fields.aliases || [])].filter(Boolean); documents.push({ id: entity.publicId, sourceId: entity.sourceId, type, canonical, label: fields.name, context: [fields.form, fields.subcategory, type === "product" ? fields.grower : "Teler"].filter(Boolean), fields, normalized: values.map(fold), tokenSet: [...new Set(values.flatMap(tokens))] }); }
    return { generationId, documents, buildMs: performance.now() - started };
}
function termScore(term, document) { let best = 0; for (let index = 0; index < document.normalized.length; index++) { const value = document.normalized[index]; const weight = index === 0 ? 120 : index === 1 ? 70 : 50; if (value === term) best = Math.max(best, weight); else if (value.startsWith(term)) best = Math.max(best, weight - 15); else if (value.includes(term)) best = Math.max(best, weight - 30); } for (const token of document.tokenSet) { if (token === term) best = Math.max(best, 45); else if (token.startsWith(term) || term.startsWith(token)) best = Math.max(best, 30); else { const d = distance(term, token); const allowed = term.length >= 7 ? 2 : term.length >= 4 ? 1 : 0; if (d <= allowed) best = Math.max(best, 20 - d * 4); } } return best; }
export function search(index, query, limit = 20) { const queryTokens = tokens(query); if (!queryTokens.length) return []; return index.documents.map((document) => { const scores = queryTokens.map((term) => termScore(term, document)); if (scores.some((score) => score === 0)) return null; const exactEntity = fold(document.label) === fold(query) ? 500 : 0; return { ...document, score: exactEntity + scores.reduce((a, b) => a + b, 0) + queryTokens.length * 10 }; }).filter(Boolean).sort((a, b) => b.score - a.score || a.canonical.localeCompare(b.canonical)).slice(0, limit); }
export function autocomplete(index, query, limit = 8) { return search(index, query, limit).map(({ id, type, canonical, label, context, score }) => ({ id, type, canonical, label: `${label}${context.length ? ` — ${context.join(" — ")}` : ""}`, score })); }
const escXml = (value) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
export function buildSitemaps({ products, growers, pages = [], routes }) { const list = (type, entities) => entities.filter((e) => e.publicationStatus === "published" && e.indexStatus === "index,follow" && e.sourceStatus !== "stale").map((entity) => ({ loc: routeCanonical(routes, type, entity.sourceId), lastmod: entity.publicContentModifiedAt || null })).filter((row) => row.loc); const maps = { products: list("product", products), growers: list("grower", growers), pages: list("page", pages) }; const urlset = (rows) => `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${rows.map((row) => `<url><loc>${escXml(`https://weedinfo.nl${row.loc}`)}</loc>${row.lastmod ? `<lastmod>${escXml(row.lastmod)}</lastmod>` : ""}</url>`).join("")}</urlset>`; return { maps, xml: Object.fromEntries(Object.entries(maps).map(([key, rows]) => [key, urlset(rows)])), index: `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${Object.entries(maps).filter(([, rows]) => rows.length).map(([key]) => `<sitemap><loc>https://weedinfo.nl/sitemap-${key}.xml</loc></sitemap>`).join("")}</sitemapindex>` }; }
