/* eslint-disable no-restricted-globals */
import { GetDataType, listPageSize, ListType } from "../types/data";
import { processList } from "../longProcesses/enums";
import { ShopType } from "../types/shop";

export const getShopData = (): Promise<Array<ShopType>> => {
    console.log("start shop fetching")
    return new Promise((resolve) => {
        setTimeout(() => {
            console.log("done fetching")
            resolve([
                {
                    id: 1,
                    lat: 51.83917,
                    lng: 4.17000,
                    name: 'John & Co. Hellevoetsluis',
                    rating: 4.8,
                    logo: 'https://images.squarespace-cdn.com/content/v1/62641230d40b510e5460b896/ae681b41-fa2d-4074-b4e1-bedd0fa4269a/Untitled+design+%288%29.png?format=1500w',
                    promo: true,
                    pickup: true,
                    drive: true,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 2,
                    lat: 51.82278,
                    lng: 4.13025,
                    name: 'Barbershop',
                    rating: 4,
                    logo: 'https://www.jouwcoffeeshop.nl/wp-content/uploads/2013/12/barbershop-logo.png',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 3,
                    lat: 51.92155,
                    lng: 4.24691,
                    name: 'Quasi',
                    rating: 4.3,
                    logo: 'https://lh3.googleusercontent.com/a-/ALV-UjWAllA8FEMizhBziJkTCQpaP-jCnJ7xrDvkj4JSDI9mMSHh0QU=w60-h60-p-rp-mo-br100',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 4,
                    lat: 52.15388,
                    lng: 5.538677,
                    name: 'Horizon',
                    rating: 4.2,
                    logo: 'https://lh3.googleusercontent.com/p/AF1QipO4uOG1Q5PZen7TeyFlGth_gnuxnDnkfPtf6Ite=s680-w680-h510',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 5,
                    lat: 52.17823,
                    lng: 5.41412,
                    name: 'Take a Break BV',
                    rating: 4.6,
                    logo: 'https://lh3.googleusercontent.com/p/AF1QipMff6--ixnYUJU8bdKUK6nq1PuIoBK4cKtlhJnI=s680-w680-h510',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 6,
                    lat: 52.16475,
                    lng: 5.36974,
                    name: 'DE LOODS Amersfoot',
                    rating: 4.8,
                    logo: 'https://lirp.cdn-website.com/3bb524ba/dms3rep/multi/opt/ARISTA-LOGO-ZWART-1-81h.png',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 7,
                    lat: 52.36296,
                    lng: 4.88522,
                    name: 'The Rookies',
                    rating: 4.6,
                    logo: 'https://instagram.frtm1-1.fna.fbcdn.net/v/t51.2885-15/387754467_841239464292007_2711571772541717475_n.jpg?stp=dst-jpg_s150x150&_nc_ht=instagram.frtm1-1.fna.fbcdn.net&_nc_cat=107&_nc_ohc=33wyvZfSHEIQ7kNvgHw30ji&_nc_gid=8ce69056ce0f430f89bbdff769c42937&edm=APs17CUBAAAA&ccb=7-5&oh=00_AYCFErYd9IkJ2q2bx1juHEosp66IDUrY2faMhNOHu1Vwmg&oe=6700A178&_nc_sid=10d13b',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 8,
                    lat: 52.35877,
                    lng: 4.94092,
                    name: 'The Stud',
                    rating: 4.7,
                    logo: 'https://thestud.nl/wp-content/uploads/2021/08/Stud_orogineel_transparant_witt-1024x514.png',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 9,
                    lat: 51.92359,
                    lng: 4.48581,
                    name: 'Trefpunt',
                    rating: 4.4,
                    logo: 'http://trefpunt.nl/wp-content/uploads/2019/12/Site-Logo.png',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 10,
                    lat: 52.08894,
                    lng: 5.12156,
                    name: '208',
                    rating: 3.5,
                    logo: 'https://scontent.frtm1-1.fna.fbcdn.net/v/t1.18169-9/13406769_1634356530219520_8802568096896039641_n.png?_nc_cat=109&ccb=1-7&_nc_sid=13d280&_nc_ohc=QtVFZ3rAGRMQ7kNvgHQdvMG&_nc_ht=scontent.frtm1-1.fna&oh=00_AYB-lGpUTEPRCLPvZKzP3Y5ebkvTmQf2FsSMoMg7pISmcw&oe=67224BFF',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 11,
                    lat: 51.91878,
                    lng: 4.47282,
                    name: '\'t Centrum',
                    rating: 3.9,
                    logo: '',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 12,
                    lat: 52.09503,
                    lng: 5.12262,
                    name: 'Pleasure',
                    rating: 3.9,
                    logo: '',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 13,
                    lat: 52.36525,
                    lng: 4.88581,
                    name: 'Happy Feelings',
                    rating: 4.7,
                    logo: '',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 14,
                    lat: 52.09525,
                    lng: 5.12136,
                    name: 'Freak',
                    rating: 3.9,
                    logo: '',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
                {
                    id: 15,
                    lat: 52.36485,
                    lng: 4.89794,
                    name: 'Boerejongens',
                    rating: 4.6,
                    logo: '',
                    promo: false,
                    pickup: true,
                    drive: false,
                    payByCard: true,
                    easyParking: true,
                    allowForeigns: true,
                    openFrom: '10:00AM',
                    openTill: '11:59PM',
                    distance: 0,
                },
            ]);
        }, 1000);
    });
};


self.onmessage = (e: MessageEvent<string>) => {
    const data = JSON.parse(e.data) as GetDataType;

    if (data.action !== processList.getData) {
        return;
    }
    if (data.period === "initial") {
        getShopData().then((list) => {
            return list.filter((item, index) => index < listPageSize)
        }).then((shops) => {
            const response = {
                loading: false,
                list: shops,
                page: data.thePageNumber,
            } as ListType;

            console.log(response)
            self.postMessage(JSON.stringify(response))
        })
    }
}

export { };