import { Box, Button, Chip, Container, Stack, Typography } from "@mui/material";
import OpenInNewIcon from "@mui/icons-material/OpenInNew";
import "./LegalPage.css";

type Section={title:string;body:string};
type Props={title:string;intro:string;sections:Section[];sources?:{label:string;href:string}[]};
type Page={intro:string;note:string;highlights:[string,string][];sections:Section[];sources?:{label:string;href:string}[]};

const pages:Record<string,Page>={
"Over WeedInfo":{intro:"WeedInfo maakt informatie over gereguleerde cannabisproducten en telers overzichtelijk en begrijpelijk voor volwassen consumenten.",note:"WeedInfo is een onafhankelijk informatieplatform. Je kunt hier geen cannabis kopen, bestellen of reserveren.",highlights:[["Feitelijk","Brongegevens en redactionele uitleg blijven herkenbaar gescheiden."],["Onafhankelijk","Geen verkooppunt, marktplaats of reserveringsdienst."],["Toegankelijk","Publieke kerninformatie werkt ook zonder JavaScript."]],sections:[
{title:"Waarom WeedInfo bestaat",body:"Productinformatie over cannabis kan versnipperd, technisch of moeilijk vergelijkbaar zijn. WeedInfo brengt publieke product- en telerinformatie samen in een vaste structuur, zodat bezoekers beter begrijpen naar welk product en welke productvorm zij kijken.\n\nEen vermelding is geen aanbeveling. Een populaire naam, hoge sterkte of positieve review betekent niet automatisch dat een product passend is voor een individuele gebruiker."},
{title:"Hoe informatie wordt opgebouwd",body:"Feitelijke product- en telergegevens komen uit de aangesloten bronadministratie. Algemene uitleg en informatiepagina’s worden redactioneel door WeedInfo beheerd. De herkomst van gegevens en handmatige overrides blijft afzonderlijk vastgelegd.\n\nProducten en telers worden via hun vaste identiteit gekoppeld. Namen en URL-slugs kunnen veranderen zonder dat daardoor een nieuwe entity ontstaat."},
{title:"Wat WeedInfo niet doet",body:"WeedInfo verkoopt geen cannabis, verwerkt geen bestellingen en bemiddelt niet tussen consumenten en verkooppunten. Prijzen, voorraad en beschikbaarheid worden niet gepubliceerd zolang daarvoor geen expliciet juridisch en publicatiebeleid bestaat.\n\nDe informatie is geen persoonlijk medisch of juridisch advies. Voor gezondheidsvragen is een arts de juiste gesprekspartner; voor wetgeving zijn officiële bronnen leidend."},
{title:"Kwaliteit en gebruikersbijdragen",body:"Ontbrekende informatie wordt niet automatisch aangevuld met marketingtekst. Technische fouten, ontbrekende brondata en redactionele aandachtspunten worden afzonderlijk behandeld.\n\nReviews moeten duidelijk herkenbaar zijn als gebruikersinhoud. Een review wordt pas als geverifieerd aangeduid wanneer daarvoor een betrouwbare verificatiebron beschikbaar is."}]},
"Privacyverklaring":{intro:"Hier lees je welke gegevens WeedInfo kan verwerken, waarom dat gebeurt en welke keuzes en rechten je hebt.",note:"Dataminimalisatie is het uitgangspunt: alleen gegevens verwerken die nodig zijn voor een gekozen functie.",highlights:[["Account","E-mail, profielnaam en technische accountgegevens."],["Bijdragen","Likes, reviews en vrijwillige profielinformatie."],["Leeftijd","Na controle alleen 18+-status; geen volledige geboortedatum."]],sections:[
{title:"Welke gegevens kunnen worden verwerkt?",body:"Zonder account kun je publieke informatie bekijken. Functionele lokale opslag kan worden gebruikt voor de 18+-keuze, cookievoorkeuren en offline/PWA-functies.\n\nBij registratie verwerkt de authenticatiedienst onder meer je e-mailadres en beveiligde accountgegevens. Een publiek profiel kan een profielnaam, zelfgekozen afbeelding, biografie, likes en reviews bevatten. Plaats geen gevoelige persoonsgegevens in openbare velden."},
{title:"Doelen en grondslagen",body:"Accountgegevens zijn nodig voor inloggen, profielbeheer, likes en eigen reviews. Technische gegevens kunnen nodig zijn voor beveiliging, foutopsporing en betrouwbare werking. Voor iedere verwerking is een passende AVG-grondslag nodig.\n\nNiet-noodzakelijke analytics horen alleen te laden na geldige toestemming. WeedInfo verkoopt geen persoonsgegevens en gebruikt accountgegevens niet om cannabis te verkopen."},
{title:"Leeftijd en minimale opslag",body:"De geboortedatum wordt bij registratie uitsluitend gebruikt om kalenderaccuraat vast te stellen of iemand 18 jaar is. Na een geslaagde controle hoeft de volledige datum niet in het profiel te worden bewaard; alleen de bevestigde status en het controletijdstip zijn voorzien.\n\nDe algemene age gate bewaart een tijdelijke lokale status en is geen identiteitsbewijs."},
{title:"Jouw rechten en ontbrekende productiegegevens",body:"Je kunt onder voorwaarden vragen om inzage, correctie, verwijdering, beperking of overdracht en bezwaar maken tegen bepaalde verwerkingen. De identiteit van de aanvrager moet daarbij zorgvuldig worden gecontroleerd.\n\nDe formele verwerkingsverantwoordelijke, contactroute, concrete verwerkers en bewaartermijnen moeten vóór productie definitief worden ingevuld. Deze lokale tekst verzint die gegevens niet."}],sources:[{label:"AP — Privacyrechten in de praktijk",href:"https://autoriteitpersoonsgegevens.nl/themas/basis-avg/privacyrechten-avg/voor-organisaties-privacyrechten-in-de-praktijk"},{label:"AP — Grondslagen AVG",href:"https://autoriteitpersoonsgegevens.nl/themas/basis-avg/avg-algemeen/grondslagen-avg-uitgelegd"}]},
"Cookiebeleid":{intro:"WeedInfo gebruikt functionele opslag voor essentiële keuzes en PWA-functies. Niet-noodzakelijke meting mag pas na toestemming starten.",note:"De website moet bruikbaar blijven wanneer je niet-noodzakelijke cookies weigert.",highlights:[["Functioneel","Voor leeftijdskeuze, sessie of offlinewerking."],["Analytics","Alleen na een vrije, actieve en geïnformeerde keuze."],["Controle","Weigeren en intrekken moeten eenvoudig blijven."]],sections:[
{title:"Cookies en vergelijkbare technieken",body:"Naast cookies kan een website local storage, IndexedDB en service-worker caches gebruiken. WeedInfo gebruikt lokale opslag onder meer om je tijdelijke 18+-keuze te onthouden en PWA/offlinefuncties te ondersteunen.\n\nAuthenticatie kan technische sessiegegevens gebruiken om je veilig ingelogd te houden. Verwijder je browsergegevens, dan moet je mogelijk opnieuw inloggen of een voorkeur opnieuw kiezen."},
{title:"Analytics en toestemming",body:"Niet-noodzakelijke analytics staan standaard uit en mogen alleen laden na expliciete toestemming. Doorgaan met browsen, scrollen of niets doen geldt niet als toestemming.\n\nEen geldige keuze is vrij, specifiek, geïnformeerd en ondubbelzinnig. Accepteren en weigeren horen even begrijpelijk beschikbaar te zijn."},
{title:"Toestemming intrekken",body:"Toestemming moet net zo eenvoudig kunnen worden ingetrokken als gegeven. Alleen verwijzen naar ingewikkelde browserinstellingen is niet voldoende wanneer WeedInfo zelf toestemming heeft gevraagd.\n\nEen volledige voorkeureninterface is nog een productievereiste. Tot die tijd blijft analytics technisch standaard uit zonder expliciete opgeslagen toestemming."},
{title:"Zelf lokale gegevens beheren",body:"Via je browser kun je cookies, lokale opslag en offline websitegegevens bekijken en verwijderen. Daarmee kunnen ook leeftijdsstatus, voorkeuren en offline bestanden verdwijnen.\n\nBlokkeer je alle opslag, dan kunnen inloggen, voorkeuren of offlinegebruik minder goed werken. Publieke informatie hoort online beschikbaar te blijven."}],sources:[{label:"AP — Tracking cookies",href:"https://autoriteitpersoonsgegevens.nl/themas/internet-slimme-apparaten/cookies/tracking-cookies"},{label:"AP — Heldere cookiebanners",href:"https://autoriteitpersoonsgegevens.nl/actueel/ap-pakt-misleidende-cookiebanners-aan"}]},
"Gebruiksvoorwaarden":{intro:"Deze voorwaarden beschrijven wat je van WeedInfo mag verwachten en hoe je het platform en communityfuncties zorgvuldig gebruikt.",note:"WeedInfo is een informatieplatform voor volwassenen en geen verkoop- of bemiddelingsdienst.",highlights:[["18+","Platform en registratie zijn bedoeld voor volwassenen."],["Informatie","Geen verkoopaanbod of persoonlijk medisch advies."],["Respect","Geen misleiding, reclame, intimidatie of verboden inhoud."]],sections:[
{title:"Gebruik van het platform",body:"Je mag publieke informatie raadplegen en een account gebruiken voor persoonlijke functies. Gebruik WeedInfo niet om verboden transacties te organiseren, beveiliging te omzeilen of de werking voor anderen te verstoren.\n\nGeautomatiseerd verzamelen of commercieel herpubliceren is niet toegestaan wanneer dat rechten schaadt, de dienstverlening belast of context en bronvermelding verwijdert."},
{title:"Accounts en beveiliging",body:"Je bent verantwoordelijk voor het veilig houden van je inloggegevens en activiteiten via je account. Kies geen profielnaam die zich voordoet als een andere persoon of organisatie.\n\nWijzig je wachtwoord wanneer je ongewenste toegang vermoedt. Functies kunnen worden beperkt om het platform, gebruikers of gegevens te beschermen."},
{title:"Reviews en bijdragen",body:"Plaats alleen eigen ervaringen en presenteer die niet als vaststaand medisch feit. Reclame, verkoopaanbiedingen, persoonsgegevens van anderen, bedreigingen en onrechtmatige inhoud zijn niet toegestaan.\n\nInhoud kan worden gemodereerd of verwijderd wanneer die regels schendt. Reviews zijn niet automatisch geverifieerd."},
{title:"Wijzigingen en beschikbaarheid",body:"WeedInfo streeft naar betrouwbare beschikbaarheid, maar kan onderhoud uitvoeren, functies aanpassen en fouten herstellen. Bronwijzigingen worden via de normale synchronisatie verwerkt.\n\nMateriële wijzigingen in deze voorwaarden horen duidelijk te worden gecommuniceerd en van een nieuwe datum te worden voorzien."}]},
"Disclaimer":{intro:"WeedInfo presenteert informatie zorgvuldig, maar context, brondata en regelgeving kunnen veranderen.",note:"Gebruik WeedInfo als informatiebron, niet als vervanging voor professioneel medisch of juridisch advies.",highlights:[["Geen verkoop","Geen aanbod, bestelling, reservering of bemiddeling."],["Geen advies","Geen persoonlijke medische of juridische aanbeveling."],["Bronnen wijzigen","Controleer belangrijke informatie bij een bevoegde bron."]],sections:[
{title:"Juistheid en actualiteit",body:"Product- en telergegevens kunnen uit een externe bronadministratie komen. WeedInfo kan niet garanderen dat iedere pagina op ieder moment volledig, foutloos of actueel is.\n\nOntbrekende informatie wordt niet aangevuld met verzonnen eigenschappen. Lees categorieën, beschrijvingen en reviews altijd binnen hun bron en context."},
{title:"Gezondheid en persoonlijke verschillen",body:"Effecten en risico’s verschillen per persoon, product, hoeveelheid, gebruikswijze en situatie. Reviews beschrijven individuele ervaringen en bewijzen niet dat een ander hetzelfde ervaart.\n\nNeem bij persoonlijke gezondheidsvragen, medicatie, zwangerschap of klachten contact op met een arts. Bel bij acuut gevaar 112."},
{title:"Wetgeving en eigen verantwoordelijkheid",body:"Regels kunnen wijzigen en per situatie of plaats verschillen. Raadpleeg voor actuele informatie de Rijksoverheid, wetten.overheid.nl of een bevoegde instantie.\n\nJe blijft zelf verantwoordelijk voor naleving van regels en veilige deelname aan het verkeer."},
{title:"Externe links en techniek",body:"Externe links zijn aanvullende bronnen. WeedInfo beheert deze websites niet en is niet verantwoordelijk voor wijzigingen, beschikbaarheid of hun privacypraktijken.\n\nStoringen, onderhoud of offlinegebruik kunnen betekenen dat onderdelen tijdelijk niet beschikbaar of verouderd zijn. Controleer kritieke informatie bij de oorspronkelijke bron."}]}
};

export default function LegalPage(props:Props){const page=pages[props.title]||{intro:props.intro,note:props.intro,highlights:[],sections:props.sections,sources:props.sources};return <Box component="article" className="legal-editorial"><header><Container maxWidth="md"><Chip label="WeedInfo informatie" color="success" variant="outlined"/><Typography component="h1" variant="h3" fontWeight={850}>{props.title}</Typography><Typography className="legal-lead">{page.intro}</Typography><div className="legal-note">{page.note}</div></Container></header><Container maxWidth="lg" sx={{py:{xs:4,md:6}}}><nav className="legal-toc" aria-label="Op deze pagina"><strong>Op deze pagina</strong>{page.sections.map((s,i)=><a key={s.title} href={`#sectie-${i}`}>{s.title}</a>)}</nav>{page.highlights.length>0&&<section className="legal-highlights">{page.highlights.map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span></div>)}</section>}<main className="legal-content">{page.sections.map((s,i)=><section id={`sectie-${i}`} className="legal-section" key={s.title}><Typography className="legal-kicker">{String(i+1).padStart(2,"0")}</Typography><Typography component="h2" variant="h4" fontWeight={800}>{s.title}</Typography>{s.body.split("\n\n").map(p=><p key={p}>{p}</p>)}</section>)}</main>{page.sources&&<section className="legal-sources"><Typography component="h2" variant="h5" fontWeight={800}>Officiële bronnen</Typography><Stack spacing={1}>{page.sources.map(s=><Button key={s.href} href={s.href} target="_blank" rel="noreferrer" variant="outlined" color="success" endIcon={<OpenInNewIcon/>} sx={{justifyContent:"space-between",textTransform:"none"}}>{s.label}</Button>)}</Stack></section>}<Typography variant="caption" color="text.secondary" display="block" mt={3}>Inhoud laatst gecontroleerd: september 2026.</Typography></Container></Box>}
