import { Box, Button, Chip, Container, Stack, Typography } from "@mui/material";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";
import PrivacyTipOutlinedIcon from "@mui/icons-material/PrivacyTipOutlined";
import CookieOutlinedIcon from "@mui/icons-material/CookieOutlined";
import GavelOutlinedIcon from "@mui/icons-material/GavelOutlined";
import ReportProblemOutlinedIcon from "@mui/icons-material/ReportProblemOutlined";
import OpenInNewIcon from "@mui/icons-material/OpenInNew";
import "./PlatformInfoPage.css";

type Kind = "about" | "privacy" | "cookies" | "terms" | "disclaimer";
type Config = { eyebrow: string; title: string; lead: string; note: string; icon: typeof InfoOutlinedIcon; highlights: Array<[string,string]>; sections: Array<{ id:string; title:string; paragraphs:string[]; callout?:string }>; sources?:Array<{label:string;href:string}> };

const configs: Record<Kind, Config> = {
  about: { eyebrow:"Over het platform", title:"Over WeedInfo", lead:"WeedInfo maakt informatie over gereguleerde cannabisproducten en telers overzichtelijk en begrijpelijk voor volwassen consumenten.", note:"WeedInfo is een onafhankelijk informatieplatform. Je kunt hier geen cannabis kopen, bestellen of reserveren.", icon:InfoOutlinedIcon, highlights:[["Feitelijk","Broninformatie en redactionele uitleg blijven herkenbaar gescheiden."],["Onafhankelijk","Geen verkooppunt, marktplaats of reserveringsdienst."],["Toegankelijk","Publieke kerninformatie werkt ook zonder JavaScript."]], sections:[
    {id:"doel",title:"Waarom WeedInfo bestaat",paragraphs:["Productinformatie over cannabis kan versnipperd, technisch of moeilijk vergelijkbaar zijn. WeedInfo brengt publieke product- en telerinformatie samen in een vaste structuur, zodat bezoekers beter begrijpen naar welk product en welke productvorm zij kijken.","De site richt zich op informatie en context. Een vermelding is geen aanbeveling en een hoge sterkte, populaire naam of positieve review betekent niet automatisch dat een product passend is voor een individuele gebruiker."]},
    {id:"werkwijze",title:"Hoe informatie wordt opgebouwd",paragraphs:["Feitelijke product- en telergegevens zijn afkomstig uit de aangesloten bronadministratie. Algemene uitleg en informatiepagina’s worden redactioneel door WeedInfo beheerd. Waar een redactionele of SEO-override bestaat, blijft de herkomst daarvan afzonderlijk vastgelegd.","Producten en telers worden via hun vaste identiteit gekoppeld. Namen en URL-slugs kunnen veranderen zonder dat daardoor een nieuwe entity ontstaat. Zo blijven permanente verwijzingen en onderlinge relaties betrouwbaar."]},
    {id:"grenzen",title:"Wat WeedInfo niet doet",paragraphs:["WeedInfo verkoopt geen cannabis, verwerkt geen bestelling en bemiddelt niet tussen consumenten en verkooppunten. Prijzen, voorraad en beschikbaarheid worden niet gepubliceerd zolang daarvoor geen expliciet juridisch en publicatiebeleid bestaat.","De informatie is evenmin persoonlijk medisch of juridisch advies. Voor gezondheidsvragen is een arts de juiste gesprekspartner; voor actuele wetgeving zijn officiële overheidsbronnen leidend."],callout:"Een informatief platform kan risico’s verduidelijken, maar neemt nooit de verantwoordelijkheid voor een persoonlijke keuze over."},
    {id:"verbeteren",title:"Kwaliteit en verbetering",paragraphs:["WeedInfo wordt stapsgewijs ontwikkeld. Technische fouten, ontbrekende brongegevens en redactionele aandachtspunten worden afzonderlijk behandeld, zodat ontbrekende informatie niet automatisch wordt ingevuld met marketingtekst.","Reviews en consumenteninzichten moeten duidelijk als gebruikersinhoud herkenbaar zijn. Een review wordt pas als geverifieerd aangeduid wanneer daarvoor een betrouwbare verificatiebron beschikbaar is."]}
  ]},
  privacy: { eyebrow:"Jouw gegevens", title:"Privacy bij WeedInfo", lead:"Hier lees je welke gegevens WeedInfo kan verwerken, waarom dat gebeurt en welke keuzes en rechten je hebt.", note:"Dataminimalisatie is het uitgangspunt: alleen gegevens verwerken die nodig zijn voor een gekozen functie.", icon:PrivacyTipOutlinedIcon, highlights:[["Account","E-mail, profielnaam en technische accountgegevens."],["Bijdragen","Likes, reviews en vrijwillig ingevulde profielinformatie."],["Leeftijd","Na controle alleen 18+-status en controletijdstip; geen geboortedatum."]], sections:[
    {id:"gegevens",title:"Welke gegevens kunnen worden verwerkt?",paragraphs:["Zonder account kun je de publieke informatie bekijken. Functionele lokale opslag kan worden gebruikt voor de 18+-keuze, cookievoorkeuren en offline/PWA-functies.","Bij registratie verwerkt de authenticatiedienst onder meer je e-mailadres en beveiligde accountgegevens. Het publieke profiel kan een profielnaam, zelfgekozen afbeelding, biografie, likes en reviews bevatten. Vul geen gevoelige persoonsgegevens in openbare profielvelden of reviews in." ]},
    {id:"doelen",title:"Waarom worden deze gegevens gebruikt?",paragraphs:["Accountgegevens zijn nodig om inloggen, profielbeheer, likes en eigen reviews mogelijk te maken. Technische gegevens kunnen nodig zijn voor beveiliging, foutopsporing en betrouwbare werking.","Niet-noodzakelijke analytics horen alleen te laden na een geldige keuze. WeedInfo verkoopt geen persoonsgegevens en gebruikt accountgegevens niet om cannabis te verkopen of bestellingen mogelijk te maken." ]},
    {id:"leeftijd",title:"Leeftijdscontrole en dataminimalisatie",paragraphs:["Bij registratie wordt de ingevoerde geboortedatum gebruikt om kalenderaccuraat vast te stellen of iemand 18 jaar is. Na een geslaagde controle hoeft de volledige geboortedatum niet in het profiel te worden bewaard; alleen de bevestigde status en het controletijdstip zijn voorzien.","De algemene age gate gebruikt uitsluitend een lokale status. Deze UX-controle is geen identiteitsbewijs en vervangt de afzonderlijke server-side registratiecontrole niet."],callout:"Een volledige geboortedatum wordt niet opgeslagen wanneer alleen bevestiging van 18+ nodig is."},
    {id:"rechten",title:"Jouw privacyrechten",paragraphs:["Je kunt onder voorwaarden vragen om inzage, correctie, verwijdering, beperking of overdracht van persoonsgegevens en bezwaar maken tegen bepaalde verwerkingen. Voor een verzoek moet WeedInfo de identiteit van de aanvrager zorgvuldig controleren.","De formele verwerkingsverantwoordelijke, contactroute, concrete verwerkers en bewaartermijnen moeten vóór productie definitief in deze verklaring worden opgenomen. Tot die tijd is deze pagina een transparante beschrijving van de gebouwde gegevensstromen en geen afgeronde juridische publicatie."]}
  ],sources:[{label:"AP — Privacyrechten in de praktijk",href:"https://autoriteitpersoonsgegevens.nl/themas/basis-avg/privacyrechten-avg/voor-organisaties-privacyrechten-in-de-praktijk"},{label:"AP — Grondslagen AVG",href:"https://autoriteitpersoonsgegevens.nl/themas/basis-avg/avg-algemeen/grondslagen-avg-uitgelegd"}]},
  cookies: { eyebrow:"Opslag en voorkeuren", title:"Cookies en lokale opslag", lead:"WeedInfo gebruikt functionele opslag voor essentiële keuzes en PWA-functies. Niet-noodzakelijke meting mag pas na toestemming starten.", note:"De website moet bruikbaar blijven wanneer je niet-noodzakelijke cookies weigert.", icon:CookieOutlinedIcon, highlights:[["Functioneel","Nodig voor leeftijdskeuze, sessie of offlinewerking."],["Analytics","Alleen na een vrije, actieve en geïnformeerde keuze."],["Controle","Weigeren en later intrekken moeten even duidelijk beschikbaar zijn."]], sections:[
    {id:"technieken",title:"Welke technieken gebruikt WeedInfo?",paragraphs:["Cookies zijn kleine gegevensbestanden, maar websites kunnen ook local storage, IndexedDB en service-worker caches gebruiken. WeedInfo gebruikt lokale opslag onder meer om je 18+-keuze tijdelijk te onthouden en om PWA/offlinefuncties te ondersteunen.","Authenticatie kan technische sessiegegevens gebruiken om je veilig ingelogd te houden. Het verwijderen van browsergegevens kan betekenen dat je opnieuw moet inloggen of je voorkeur opnieuw moet kiezen."]},
    {id:"analytics",title:"Analytics en toestemming",paragraphs:["Niet-noodzakelijke analytics staan standaard uit. Ze mogen alleen worden geladen nadat je daar expliciet mee instemt. Doorgaan met browsen, scrollen of niets doen geldt niet als toestemming.","Een geldige keuze moet vrij, specifiek, geïnformeerd en ondubbelzinnig zijn. Accepteren en weigeren horen even begrijpelijk te zijn; de website mag een weigering niet bestraffen door essentiële inhoud te blokkeren." ]},
    {id:"intrekken",title:"Voorkeur wijzigen of toestemming intrekken",paragraphs:["Toestemming moet net zo eenvoudig kunnen worden ingetrokken als gegeven. Alleen verwijzen naar ingewikkelde browserinstellingen is daarvoor niet voldoende wanneer WeedInfo zelf toestemming heeft gevraagd.","Een volwaardige voorkeureninterface is nog een productievereiste. Tot die tijd blijft analytics technisch standaard uit wanneer geen expliciete opgeslagen toestemming aanwezig is."],callout:"Geen keuze betekent geen toestemming voor niet-noodzakelijke analytics."},
    {id:"browser",title:"Zelf opgeslagen gegevens beheren",paragraphs:["Via je browser kun je cookies, lokale opslag en offline websitegegevens bekijken en verwijderen. Daarmee kunnen ook leeftijdsstatus, voorkeuren en offline bestanden verdwijnen.","Blokkeer je alle lokale opslag, dan kunnen inloggen, voorkeuren of offlinegebruik minder goed werken. De publieke informatie hoort online wel beschikbaar te blijven."]}
  ],sources:[{label:"AP — Tracking cookies",href:"https://autoriteitpersoonsgegevens.nl/themas/internet-slimme-apparaten/cookies/tracking-cookies"},{label:"AP — Vuistregels cookiebanners",href:"https://autoriteitpersoonsgegevens.nl/actueel/ap-pakt-misleidende-cookiebanners-aan"}]},
  terms: { eyebrow:"Afspraken voor gebruik", title:"Gebruiksvoorwaarden", lead:"Deze voorwaarden beschrijven wat je van WeedInfo mag verwachten en hoe je het platform en de communityfuncties zorgvuldig gebruikt.", note:"WeedInfo is een informatieplatform voor volwassenen en geen verkoop- of bemiddelingsdienst.", icon:GavelOutlinedIcon, highlights:[["18+","Het platform en accountregistratie zijn bedoeld voor volwassenen."],["Informatie","Geen verkoopaanbod en geen persoonlijk medisch advies."],["Respect","Geen misleiding, reclame, intimidatie of onrechtmatige inhoud."]], sections:[
    {id:"gebruik",title:"Gebruik van het platform",paragraphs:["Je mag publieke informatie raadplegen en, wanneer beschikbaar, een account gebruiken voor persoonlijke functies. Gebruik het platform niet om verboden transacties te organiseren, beveiliging te omzeilen of de werking voor anderen te verstoren.","Geautomatiseerd verzamelen, herpubliceren of commercieel exploiteren van inhoud is niet toegestaan wanneer dat rechten schaadt, de dienstverlening belast of de context en bronvermelding verwijdert." ]},
    {id:"accounts",title:"Accounts en beveiliging",paragraphs:["Je bent verantwoordelijk voor het veilig houden van je inloggegevens en voor activiteiten via je account. Kies geen profielnaam die zich voordoet als een andere persoon of organisatie.","Meld vermoed misbruik en wijzig je wachtwoord wanneer je denkt dat iemand toegang heeft. WeedInfo kan functies beperken om het platform, gebruikers of gegevens te beschermen." ]},
    {id:"bijdragen",title:"Reviews en andere gebruikersbijdragen",paragraphs:["Plaats alleen eigen ervaringen en formuleer die als persoonlijke ervaring, niet als vaststaand medisch feit. Reclame, verkoopaanbiedingen, persoonsgegevens van anderen, bedreigingen en discriminerende of onrechtmatige inhoud zijn niet toegestaan.","Gebruikersinhoud kan worden gemodereerd of verwijderd wanneer die de regels schendt. Een review is niet automatisch geverifieerd; een verificatielabel mag alleen worden gebruikt wanneer een betrouwbare koppeling dat ondersteunt." ]},
    {id:"beschikbaarheid",title:"Wijzigingen en beschikbaarheid",paragraphs:["WeedInfo streeft naar betrouwbare informatie en beschikbaarheid, maar kan onderhoud uitvoeren, functies aanpassen of fouten herstellen. Een wijziging in brondata kan zichtbaar worden via de normale synchronisatie.","Deze voorwaarden mogen worden bijgewerkt wanneer functies, regelgeving of verantwoordelijkheden veranderen. Materiële wijzigingen horen duidelijk te worden gecommuniceerd en van een nieuwe datum te worden voorzien."]}
  ]},
  disclaimer: { eyebrow:"Grenzen van de informatie", title:"Disclaimer", lead:"WeedInfo doet moeite om informatie zorgvuldig te presenteren, maar context, brondata en regelgeving kunnen veranderen.", note:"Gebruik WeedInfo als informatiebron, niet als vervanging voor professioneel medisch of juridisch advies.", icon:ReportProblemOutlinedIcon, highlights:[["Geen verkoop","Geen aanbod, bestelling, reservering of bemiddeling."],["Geen advies","Geen persoonlijke medische, juridische of gebruiksaanbeveling."],["Bronnen veranderen","Controleer belangrijke beslissingen bij een bevoegde actuele bron."]], sections:[
    {id:"juistheid",title:"Juistheid en actualiteit",paragraphs:["Product- en telergegevens kunnen uit een externe bronadministratie komen. WeedInfo probeert wijzigingen zorgvuldig te synchroniseren, maar kan niet garanderen dat iedere pagina op ieder moment volledig, foutloos of actueel is.","Ontbrekende informatie wordt niet automatisch aangevuld met verzonnen eigenschappen. Meldingen, categorieën en beschrijvingen moeten worden gelezen binnen de vermelde bron en context." ]},
    {id:"gezondheid",title:"Gezondheid en persoonlijke verschillen",paragraphs:["Effecten en risico’s van cannabis verschillen per persoon, product, hoeveelheid, gebruikswijze en situatie. Reviews beschrijven individuele ervaringen en bewijzen niet dat een ander hetzelfde zal ervaren.","Neem voor persoonlijke gezondheidsvragen, medicatie, zwangerschap of aanhoudende klachten contact op met een arts. Bel bij een acute gevaarlijke situatie 112."],callout:"Een productpagina of review is nooit een doseringsadvies of garantie op een bepaald effect."},
    {id:"wetgeving",title:"Wetgeving en verantwoordelijkheid",paragraphs:["Regels kunnen wijzigen en per situatie of plaats verschillen. Raadpleeg voor actuele juridische informatie de Rijksoverheid, wetten.overheid.nl of een bevoegde instantie.","Je blijft zelf verantwoordelijk voor je keuzes, naleving van regels en veilige deelname aan het verkeer. Onder invloed deelnemen aan het verkeer is onveilig." ]},
    {id:"links",title:"Externe links en beschikbaarheid",paragraphs:["Links naar externe websites zijn bedoeld als aanvullende bron. WeedInfo beheert die websites niet en is niet verantwoordelijk voor wijzigingen, beschikbaarheid of hun privacypraktijken.","Technische storingen, onderhoud of offlinegebruik kunnen betekenen dat onderdelen tijdelijk niet beschikbaar of verouderd zijn. Kritieke informatie moet altijd bij de oorspronkelijke bevoegde bron worden gecontroleerd."]}
  ]}
};

export default function PlatformInfoPage({ kind }: { kind: Kind }) {
  const page=configs[kind], Icon=page.icon;
  return <Box component="article" className="platform-page"><header className="platform-hero"><Container maxWidth="md"><Chip label={page.eyebrow} color="success" variant="outlined"/><Typography component="h1" variant="h3" fontWeight={850}>{page.title}</Typography><Typography className="platform-lead">{page.lead}</Typography><div className="platform-note"><Icon/><span>{page.note}</span></div></Container></header><Container maxWidth="lg" sx={{py:{xs:4,md:6}}}><nav className="platform-toc" aria-label="Op deze pagina"><strong>Op deze pagina</strong>{page.sections.map(section=><a key={section.id} href={`#${section.id}`}>{section.title}</a>)}</nav><section className="platform-highlights">{page.highlights.map(([title,text])=><div key={title}><strong>{title}</strong><span>{text}</span></div>)}</section><main className="platform-content">{page.sections.map((section,index)=><section className="platform-section" id={section.id} key={section.id}><Typography className="platform-kicker">{String(index+1).padStart(2,"0")}</Typography><Typography component="h2" variant="h4" fontWeight={800}>{section.title}</Typography>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{section.callout&&<div className="platform-callout">{section.callout}</div>}</section>)}</main>{page.sources&&<section className="platform-sources"><div><Typography className="platform-kicker">Officiële uitleg</Typography><Typography component="h2" variant="h5" fontWeight={800}>Bronnen en privacy-informatie</Typography></div><Stack spacing={1}>{page.sources.map(source=><Button key={source.href} href={source.href} target="_blank" rel="noreferrer" variant="outlined" color="success" endIcon={<OpenInNewIcon/>} sx={{justifyContent:"space-between",textTransform:"none"}}>{source.label}</Button>)}</Stack></section>}<Typography variant="caption" color="text.secondary" display="block" mt={3}>Inhoud laatst gecontroleerd: september 2026.</Typography></Container></Box>;
}
